//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnofiFrameAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public int Id { get; set; }
        public string MSISDN { get; set; }
        public string IMEI { get; set; }
        public string IMSI { get; set; }
        public Nullable<bool> IsRequest { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TargetName { get; set; }
    }
}
