//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enofibom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapOfflineEntities : DbContext
    {
        public MapOfflineEntities()
            : base("name=MapOfflineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogEvent> LogEvents { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
    }
}
