//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enofibom
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatorCell
    {
        public int Id { get; set; }
        public string CellName { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string btsId { get; set; }
        public string lcrId { get; set; }
        public string TAC { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
